### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by nicolasbadia** [lsimediasarl/OpenTileServerDebian#2]
The following packages were missing for me:

    postgresql-9.6-postgis-scripts
    postgresql-9.6-postgis-2.3

The commande `psql -c "CREATE EXTENSION postgis;" -d ${OSM_DB}` would not works without them.

**Comment by sbodmer** [comment]
Hi, thanks for your feedback.
Under Debian 9 (stretch), the `postgis` package should resolve the two missing packages that you
mention.
Which version of Debian are you using ?
I tested the script with a barbone Debian 9 install and everything works as intended (no error during extension creation)

**Comment by nicolasbadia** [comment]
I'm running debian 9.5.
From this page: https://packages.debian.org/fr/stretch/postgis I do not see the packages being included.

**Comment by sbodmer** [comment]
Your are right Nicolas... The docs says so...
...but when I do 
```
root@debian-labo:~# apt install postgis
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core fonts-droid-fallback fonts-noto-mono ghostscript   
 ...
The following NEW packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core fonts-droid-fallback fonts-noto-mono ghostscript
  odbcinst1debian2 poppler-data postgis postgis-doc postgresql-9.6 postgresql-9.6-postgis-2.3
postgresql-9.6-postgis-2.3-scripts postgresql-client-9.6 postgresql-client-common
postgresql-common postgresql-contrib-9.6 proj-bin proj-data python-talloc qdbus qt-at-spi qtchooser qtcore4-l10n samba-libs
...
0 upgraded, 291 newly installed, 0 to remove and 0 not upgraded.
Need to get 151 MB of archives.
After this operation, 700 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```
the package are in the list...
...so I'm a bit confused...
I will investigate to check why the postgis package will not install the recommended ones in your case.

**Comment by sbodmer** [comment]
Grrrr... I cannot reproduce your situation.
I Installed a Barbone Debian 9.5 (expert install with only ssh and basic utilities).
I started the script and everything was installed correctly...

So I suppose... you have disabled the "recommended" install flag of packages in your apt config
_https://unix.stackexchange.com/questions/122289/why-install-recommends-default-is-true_

Can you confirm me you have set the default value to false ?

**Comment by nicolasbadia** [comment]
That's it!
`cat /etc/apt/apt.conf.d/00InstallRecommends` says:

    APT::Install-Recommends "false";

**Comment by nicolasbadia** [comment]
Maybe the best solution would be to use the flag `--install-recommends`.

**Comment by sbodmer** [comment]
Thanks, I added the --install-recommends in the apt option.
